SystemOrganization addCategory: #MetaDDS!
SystemOrganization addCategory: #'MetaDDS-Encoding'!
SystemOrganization addCategory: #'MetaDDS-Kernel'!
SystemOrganization addCategory: #'MetaDDS-Proxy'!
SystemOrganization addCategory: #'MetaDDS-Reflection'!
SystemOrganization addCategory: #'MetaDDS-TypesDefinition'!
SystemOrganization addCategory: #'MetaDDS-TypesMarshalling'!
SystemOrganization addCategory: #'MetaDDS-Util'!
