language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Squeak-trunk
  - Squeak-5.0

  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
  - Pharo-4.0

  - GemStone-3.3.0
  - GemStone-3.2.12
  - GemStone-3.1.0.6
